### ISSUE TITLE
Refactoring - 특정 일정 조회 시 응답 내용 추가하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#101]
✏️Description
- 특정 일정 조회 시 응답 내용 추가하기

✅TODO
-
- [x] 위도, 경도, 콘텐츠 라벨, 지역 라벨, 제목 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#101 created for issue: Refactoring - 특정 일정 조회 시 응답 내용 추가하기

**Comment by numerical43** [comment]
🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊

**Comment by fakerdeft** [comment]
> 🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊

제정신이야
