### ISSUE TITLE
Feature - 좋아요한 컨텐츠 조회 API 구현

### ISSUE THREAD

**Issue by Subak-Uncle** [Adregamdi/Backend#102]
✏️Description
- `마이페이지`에서 사용될 좋아요한 `전체`, '장소', '쇼츠', '여행기'를 리스트 형태로 조회하는 API를 구현하겠습니다.

✅TODO
-
- [ ] 전체 컨텐츠 인터페이스 개설
- [ ] 형태에 맞게 컨텐츠 DTO 오버라이딩
- [ ] 무한 스크롤 형태로 조회

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch feature/#102 created for issue: Feature - 좋아요한 컨텐츠 조회 API 구현

**Comment by numerical43** [comment]
🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊
