### ISSUE TITLE
Feature - 최근 등록된 여행기 조회 API 구현하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#105]
✏️Description
- 최근 등록된 여행기 조회 API 구현하기

✅TODO
-
- [x] 최근 등록된 여행기 조회 API

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch feature/#105 created for issue: Feature - 최근 등록된 여행기 조회 API 구현하기
