### ISSUE TITLE
Feature - 특정 장소의 전체 사진/리뷰 조회 API 구현하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#106]
✏️Description
- 특정 장소의 전체 사진/리뷰 조회 API 구현하기

✅TODO
-
- [x] 전체 사진 조회 api
- [x] 전체 리뷰 조회 api

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch feature/#106 created for issue: Feature - 특정 장소의 전체 사진/리뷰 조회 API 구현하기
