### ISSUE TITLE
Bugfix - 검색 api 안 되던 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#112]
🗺️Location
- 검색 api

🤷WHAT
- 검색이 안 됨

✏️HOW
- dto 인스턴스 생성 시 주소 파라미터 넣기

**Comment by Subak-Uncle** [comment]
Branch bugfix/#112 created for issue: Bugfix - 검색 api 안 되던 버그 수정하기
