### ISSUE TITLE
Refactoring - 여행기 등록 기능 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#114]
✏️Description
- 리뷰는 중간 저장이 가능하도록 구현하기

✅TODO
- [x] 리뷰 등록 api 수정하기
- [x] 여행기 등록 api 수정하기

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#114 created for issue: Refactoring - 여행기 등록 기능 수정하기
