### ISSUE TITLE
Refactoring - 일정 조회 API 외

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#120]
✏️Description
- 일정 조회 api 수정 외

✅TODO
-
- [x] 일정 응답에 리뷰 id 추가
- [x] 장소 엔티티에 contentsId 추가
- [x] 전화번호, 주소 null 처리

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#120 created for issue: Refactoring - 일정 조회 API 외
