### ISSUE TITLE
Bugfix - 회원의 콘텐츠들이 안 보이는 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#143]
🗺️Location
- DB

🤷WHAT
- memberId 타입 문제
어떤 문제가 발생했는지

✏️HOW
- 회원 테이블의 id를 String으로 넣기로 결정

**Comment by Subak-Uncle** [comment]
Branch bugfix/#143 created for issue: Bugfix - 회원의 콘텐츠들이 안 보이는 버그 수정하기
