### ISSUE TITLE
Refactoring - 특정 여행기 조회 시 작성자 정보 추가하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#148]
✏️Description
- 특정 여행기 조회 시 작성자 정보 추가하기

✅TODO
-
- [x] 응답에 작성자 이름, 프로필 사진, 핸들 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#148 created for issue: Refactoring - 특정 여행기 조회 시 작성자 정보 추가하기
