### ISSUE TITLE
Refactoring - 예외 응답 시 최대한 4xx 코드로 가도록 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#149]
✏️Description
- 5xx로 가는 예외들 최대한 4xx로 갈 수 있도록 수정하기

✅TODO
-
- [x] 부정합 데이터들이 들어왔을 때 예외 처리 추가하기
- [x] aop 로깅 가독성 개선하기

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#149 created for issue: Refactoring - 예외 응답 시 4xx 코드로 가도록 수정하기
