### ISSUE TITLE
Refactoring - 부정합 데이터 필터링 추가하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#151]
✏️Description
- 부정합 데이터들이 들어왔을 때 예외 처리 추가하기

✅TODO
-
- [ ] 요청 파라미터 예외 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#151 created for issue: Refactoring - 부정합 데이터 필터링 추가하기
