### ISSUE TITLE
Refactoring - 최적 거리 정렬 API HTTP 메서드 바꾸기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#155]
✏️Description
- 최적 거리 정렬 API HTTP 메서드 바꾸기

✅TODO
-
- [x] post로 바꾸기

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#155 created for issue: Refactoring - 최적 거리 정렬 API HTTP 메서드 바꾸기
