### ISSUE TITLE
Bugfix - 일정에 많이 추가된 장소 API 이미지 안 담기는 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#168]
🗺️Location
- 일정에 많이 추가된 장소 API

🤷WHAT
- 첫 번째 장소엔 이미지가 중복해서 담기고 이후 장소들은 아예 안 담김
어떤 문제가 발생했는지

✏️HOW
- 쿼리문 수정하기
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#168 created for issue: Bugfix - 일정에 많이 추가된 장소 API 이미지 안 담기는 버그 수정하기
