### ISSUE TITLE
Bugfix - 사진 리뷰 개수 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#170]
🗺️Location
- 일정에 많이 추가된 장소 api

🤷WHAT
- 사진 리뷰 개수가 이상하게 나옴
어떤 문제가 발생했는지

✏️HOW
- 사진이 있는 리뷰의 개수만 계산하는 서브쿼리를 사용
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#170 created for issue: Bugfix - 사진 리뷰 개수 버그 수정하기
