### ISSUE TITLE
Bugfix - 여행기 등록 안 되는 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#172]
🗺️Location
- 여행기 등록 api

🤷WHAT
- 장소 리뷰 id가 비정상 데이터라 등록이 안 됨
어떤 문제가 발생했는지

✏️HOW
- 일정 조회 api에서 장소 id를 조회시키고 있었기 때문에 장소 리뷰 id 추가
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch api/#172 created for issue: Bugfix - 여행기 등록 안 되는 버그 수정하기
