### ISSUE TITLE
Bugfix - 특정 여행기 조회 API 응답 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#174]
🗺️Location
- 특정 여행기 조회 api

🤷WHAT
- 데이터는 가는데 key 불일치
어떤 문제가 발생했는지

✏️HOW
- 응답에서 key 이름 수정, 좌표 추가
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch api/#174 created for issue: Bugfix - 특정 여행기 조회 API 응답 수정하기
