### ISSUE TITLE
Bugfix - 장소 목록 키 이름 변경

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#176]
🗺️Location
- 특정 여행기 조회 api

🤷WHAT
- 장소 목록 키 이름 불일치
어떤 문제가 발생했는지

✏️HOW
- 이름 placeList로 수정
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#176 created for issue: Bugfix - 장소 목록 키 이름 변경
