### ISSUE TITLE
Bugfix - 내 여행기 조회 시 프사 안 보이는 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#182]
🗺️Location
- 내 여행기 조회 api

🤷WHAT
- 내 여행기 조회 시 프사 안 보이는 버그
어떤 문제가 발생했는지

✏️HOW
- memberProfile 추가
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#182 created for issue: Bugfix - 내 여행기 조회 시 프사 안 보이는 버그 수정하기
