### ISSUE TITLE
Bugfix - 인기 장소 조회 시 사진 리뷰 수 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#183]
🗺️Location
- 일정에 많이 추가된 장소 api

🤷WHAT
- 사진 리뷰 수 제대로 측정 안됨
어떤 문제가 발생했는지

✏️HOW
- 쿼리문 수정
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#183 created for issue: Bugfix - 인기 장소 조회 시 사진 리뷰 수 버그 수정하기
