### ISSUE TITLE
Bugfix - 여행기 조회 api 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#187]
🗺️Location
- 내 여행기 조회 api, 특정 여행기 조회 api

🤷WHAT
- 프로필 쿼리문 없음, id값 null 처리 안 됨
어떤 문제가 발생했는지

✏️HOW
- 프로필 쿼리문 추가, id null 처리
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#187 created for issue: Bugfix - 여행기 조회 api 버그 수정하기
