### ISSUE TITLE
Bugfix - 차단 해제 안 되는 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#195]
🗺️Location
- 차단 해제 api

🤷WHAT
- 차단 해제가 안 됨
어떤 문제가 발생했는지

✏️HOW
- deleteById 메서드 사용
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#195 created for issue: Bugfix - 차단 해제 안 되는 버그 수정하기
