### ISSUE TITLE
Bugfix - 장소 데이터 일부 안 들어가는 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#197]
🗺️Location
- 장소 등록 api

🤷WHAT
- 일부 데이터 안 들어가짐
어떤 문제가 발생했는지

✏️HOW
- 생성할 때 contentsId 필드 공백으로 입력
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#197 created for issue: Bugfix - 장소 데이터 일부 안 들어가는 버그 수정하기
