### ISSUE TITLE
Bugfix - 일정/여행기 삭제 시 자식 테이블 삭제 안 되던 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#210]
🗺️Location
- 일정/여행기 삭제 api

🤷WHAT
- 자식 테이블들 삭제 안 됨
어떤 문제가 발생했는지

✏️HOW
- 삭제 로직 추가
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#210 created for issue: Bugfix - 일정/여행기 삭제 시 자식 테이블 삭제 안 되던 버그 수정하기
