### ISSUE TITLE
Refactoring - 회원 탈퇴 시 해당 회원의 콘텐츠 삭제 로직 추가하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#217]
✏️Description
- 회원 탈퇴 시 해당 회원의 콘텐츠 삭제 로직 추가하기

✅TODO
-
- [x] 해당 회원의 콘텐츠 삭제

**Comment by Subak-Uncle** [comment]
Branch refactor/#217 created for issue: Refactoring - 회원 탈퇴 시 해당 회원의 콘텐츠 삭제 로직 추가하기
