### ISSUE TITLE
Bugfix - 쇼츠 조회 시 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#227]
🗺️Location
- 특정 쇼츠 조회 api 

🤷WHAT
- 장소/여행기 id가 0일 경우 예외 처리 안 됨
어떤 문제가 발생했는지

✏️HOW
- id값 0 예외 처리
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#227 created for issue: Bugfix - 쇼츠 조회 시 버그 수정하기
