### ISSUE TITLE
Refactoring - 여행기 작성 시 일정 메모 추가하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#229]
✏️Description
- 여행기 작성 시 일정 메모 추가하기

✅TODO
-
- [x] 여행기 등록 api 요청에 날짜 별 메모 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#229 created for issue: Refactoring - 여행기 작성 시 일정 메모 추가하기
