### ISSUE TITLE
Bugfix - 알림 삭제 안 되던 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#239]
🗺️Location
- 알림 삭제 메서드

🤷WHAT
- 콘텐츠 소유자 id 혼동
어떤 문제가 발생했는지

✏️HOW
- 알림 삭제하는 주체와 콘텐츠 소유자 id 구분
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#239 created for issue: Bugfix - 알림 삭제 안 되던 버그 수정하기
