### ISSUE TITLE
Refactoring - 자신의 알림은 조회 안 되도록 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#241]
✏️Description
- 자신의 알림은 조회 안 되도록 수정하기

✅TODO
-
- [x] 자신의 알림은 조회 안 되도록 수정

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#241 created for issue: Refactoring - 자신의 알림은 조회 안 되도록 수정하기
