### ISSUE TITLE
Refactoring - 좋아요 삭제 시 알림도 존재하는 알림만 삭제 가능하도록 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#243]
✏️Description
- 존재하는 알림에 대해서만 삭제 가능하도록 수정하기

✅TODO
-
- [x] 알림 삭제 메서드 로직 수정

**Comment by Subak-Uncle** [comment]
Branch refactor/#243 created for issue: Refactoring - 좋아요 삭제 시 알림도 존재하는 알림만 삭제 가능하도록 수정하기
