### ISSUE TITLE
Refactoring - 접속 시간 체크 메서드 사용 위치 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#245]
✏️Description
- 접속 시간 체크 메서드 사용 위치 수정하기

✅TODO
-
- [x] 접속 시간 체크 메서드 사용 위치 수정

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#245 created for issue: Refactoring - 접속 시간 체크 메서드 사용 위치 수정하기
