### ISSUE TITLE
Refactoring - 일정에 많이 추가된 장소 리스트 캐싱하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#247]
✏️Description
- 일정에 많이 추가된 장소 리스트 캐싱하기
  - 조회 api 호출마다 db에서 불러오는 방식에서 인메모리(레디스)에서 데이터 꺼내오는 방식으로 수정하기

✅TODO
-
- [x] 일정에 많이 추가된 장소 리스트 주기적으로 레디스에 등록
- [x] 일정에 많이 추가된 장소 리스트 조회 api 로직 수정

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#247 created for issue: Refactoring - 일정에 많이 추가된 장소 리스트 캐싱하기
