### ISSUE TITLE
Refactoring - 최적 거리 정렬 알고리즘 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#249]
✏️Description
- 최적 거리 정렬 알고리즘 수정하기

✅TODO
-
- [ ] 최적 거리 정렬 알고리즘 수정하기

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#249 created for issue: Refactoring - 최적 거리 정렬 알고리즘 수정하기
