### ISSUE TITLE
Bugfix - 장소 추가 시 카운트 변동 안 되던 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#250]
🗺️Location
- 장소 카운트 추가 메서드

🤷WHAT
- 기존 카운트 기반으로 계산을 하지 않아서 카운트 증가/감소 안됐었음
어떤 문제가 발생했는지

✏️HOW
- 기존 카운트에서 더하거나 빼는 로직으로 수정
어떻게 해결했는지

**Comment by Subak-Uncle** [comment]
Branch bugfix/#250 created for issue: Bugfix - 장소 추가 시 카운트 변동 안 되던 버그 수정하기
