### ISSUE TITLE
Refactoring - 인기 장소 조회 쿼리 수정하기 등

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#252]
✏️Description
- 인기 장소 조회 시 조건이 쿼리 수정하기
- 일정 생성 시 시작 날짜 예외 처리하기

✅TODO
-
- [x] 인기 장소 조회 쿼리 수정하기
- [x] 일정 생성 시 시작 날짜 예외 처리 추가

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#252 created for issue: Refactoring - 인기 장소 조회 쿼리 수정하기 등
