### ISSUE TITLE
Bugfix - 인기 장소 조회 쿼리 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#254]
🗺️Location
- 인기 장소 조회 쿼리

🤷WHAT
- url 그룹 바이 안 되어있다고 에러남
어떤 문제가 발생했는지

✏️HOW
- 그룹 바이에 url 넣어줌
어떻게 해결했는지

✅TODO
-
- [ ] 
- [ ] 
- [ ] 

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch bugfix/#254 created for issue: Bugfix - 인기 장소 조회 쿼리 버그 수정하기
