### ISSUE TITLE
Refactoring - 인기 장소 업데이트 메서드에 로그 추가하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#256]
✏️Description
- 인기 장소 업데이트 메서드에 로그 추가하기

✅TODO
-
- [x] 인기 장소 업데이트 메서드에 로그 추가하기

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#256 created for issue: Refactoring - 인기 장소 업데이트 메서드에 로그 추가하기
