### ISSUE TITLE
Feature - 선택한 장소 주변 가까운 장소 추천 API 구현하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#36]
✏️Description
- 외부 API 사용해서 선택한 장소 주변 가까운 장소 추천 API 구현하기

✅TODO
- [x] 선택한 장소 주변 가까운 장소 추천 API

**Comment by Subak-Uncle** [comment]
Branch feature/#36 created for issue: Feature - 선택한 장소 주변 가까운 장소 추천 API 구현하기
