### ISSUE TITLE
Refactoring - 장소 검색 API에 여행기/쇼츠 검색도 추가하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#39]
✏️Description
- 장소 검색 API에 여행기/쇼츠 검색도 추가하기

✅TODO
- [x] 여행기 검색 기능
- [x] 쇼츠 검색 기능

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#39 created for issue: Refactoring - 장소 검색 API에 여행기/쇼츠 검색도 추가하기
