### ISSUE TITLE
Refactoring - 회원 엔티티 컬럼 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#40]
✏️Description
- 회원 엔티티 컬럼 수정하기

✅TODO
- [x] 이름 컬럼 추가하기
- [x] 닉네임 컬럼명을 핸들로 수정하기
- [x] 회원 조회 API 수정하기
- [x] 회원 수정 API 구현하기

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#40 created for issue: Refactoring - 회원 엔티티 컬럼 수정하기
