### ISSUE TITLE
Feature - 일정에 많이 추가된 장소 리스트 조회 API 구현하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#43]
✏️Description
- 일정에 많이 추가된 장소 리스트 조회 API 구현하기

✅TODO
-
- [x] 장소 엔티티에 카운트 컬럼 추가하기
- [x] 일정 등록 시 해당 장소 카운트 시키기
- [x] 카운트 순 조회하기

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch feature/#43 created for issue: Feature - 일정에 많이 추가된 장소 리스트 조회 API 구현하기
