### ISSUE TITLE
Bugfix - 장소 검색 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#76]
🗺️Location
- 검색 api

🤷WHAT
- 장소 검색
어떤 문제가 발생했는지

✏️HOW
- 쿼리 날리고 결과 받을 때 dto 필드 추가

**Comment by Subak-Uncle** [comment]
Branch bugfix/#76 created for issue: Bugfix - 장소 검색 버그 수정하기
