### ISSUE TITLE
Bugfix - 일정 등록/수정 API 버그 수정하기

### ISSUE THREAD

**Issue by fakerdeft** [Adregamdi/Backend#91]
🗺️Location
- 일정 등록/수정 api 요청 시

🤷WHAT
- 수정 시 travelDay 테이블에 데이터가 새로 들어감
어떤 문제가 발생했는지

✏️HOW
- 등록/수정 로직 수정

**Comment by Subak-Uncle** [comment]
Branch bugfix/#91 created for issue: Bugfix - 일정 등록/수정 API 버그 수정하기
