### ISSUE TITLE
Refactoring - 좋아요 api 분리

### ISSUE THREAD

**Issue by Subak-Uncle** [Adregamdi/Backend#94]
✏️Description
- 좋아요 api를 '장소', '여행기', '쇼츠'로 분리하겠습니다.

✅TODO
- API 분리하기

🐾ETC
-

**Comment by Subak-Uncle** [comment]
Branch refactor/#94 created for issue: Refactoring - 좋아요 api 분리

**Comment by silverpoodle** [comment]
🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊

**Comment by Subak-Uncle** [comment]
죄송한데,,,🙏 감귤 서리 금지세요^^
